CREATE TABLE pull_request_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_number INTEGER NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    author_login VARCHAR(100),
    source_branch VARCHAR(255),
    target_branch VARCHAR(255),
    total_additions INTEGER DEFAULT 0,
    total_deletions INTEGER DEFAULT 0,
    changed_files_count INTEGER DEFAULT 0,
    labels TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    repository_id BIGINT NOT NULL REFERENCES repositories(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pr_number_repository UNIQUE (pr_number, repository_id)
);

CREATE INDEX idx_pull_requests_repository_id ON pull_request_records(repository_id);
CREATE INDEX idx_pull_requests_status ON pull_request_records(status);
