CREATE TABLE scoring_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    rule_type VARCHAR(20) NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    threshold_value DOUBLE PRECISION,
    repository_id BIGINT REFERENCES repositories(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scoring_rules_repository_id ON scoring_rules(repository_id);
CREATE INDEX idx_scoring_rules_enabled ON scoring_rules(enabled);
