CREATE TABLE score_reasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_code VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    impact_score DOUBLE PRECISION NOT NULL,
    positive BOOLEAN NOT NULL DEFAULT FALSE,
    score_result_id BIGINT NOT NULL REFERENCES score_results(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_score_reasons_score_result_id ON score_reasons(score_result_id);
